include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/gen/**
    - build/**
    - ios/**
    - android/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    unawaited_futures: true

