name: ramen_radar
description: Ramen Radar app per README plan.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter

  # State management / DI
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing (planned)
  auto_route: ^7.9.2

  # Models / JSON
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Env
  flutter_dotenv: ^5.1.0

  # Location / Permissions / Map (planned)
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.1

  # Networking
  dio: ^5.7.0

  # External intents
  url_launcher: ^6.3.1

  # Connectivity
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: assets/icons/app_icon.png
  android_12:
    image: assets/icons/app_icon.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icons/app_icon.png
